sonar.projectKey=hangmanServidor
sonar.working.directory=C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer
sonar.pullrequest.cache.basepath=C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer

08BCF73D-F901-40C3-8524-4C064DF723D4.sonar.projectKey=hangmanServidor:08BCF73D-F901-40C3-8524-4C064DF723D4
08BCF73D-F901-40C3-8524-4C064DF723D4.sonar.projectName=HangmanServer
08BCF73D-F901-40C3-8524-4C064DF723D4.sonar.projectBaseDir=C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer
08BCF73D-F901-40C3-8524-4C064DF723D4.sonar.sourceEncoding=utf-8
08BCF73D-F901-40C3-8524-4C064DF723D4.sonar.tests=
08BCF73D-F901-40C3-8524-4C064DF723D4.sonar.sources=\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\BusinessLogic\\AccountManager.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\BusinessLogic\\CatalogManager.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\BusinessLogic\\GameManager.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\BusinessLogic\\GameRoom.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\BusinessLogic\\MatchmakingManager.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\BusinessLogic\\ScoreManager.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Contracts\\IAccountService.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Contracts\\ICatalogService.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Contracts\\IGameService.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Contracts\\IMatchmakingService.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Contracts\\IScoreService.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DataAccess\\Categories.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DataAccess\\IRepository.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DataAccess\\IUnitOfWork.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DataAccess\\Languages.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DataAccess\\Matches.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DataAccess\\MatchStatuses.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DataAccess\\Repository.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DataAccess\\sysdiagrams.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DataAccess\\UnitOfWork.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DataAccess\\Users.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DataAccess\\Words.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DTOs\\AvailableMatchDTO.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DTOs\\CategoryDTO.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DTOs\\GameContextDTO.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DTOs\\GameEndDTO.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DTOs\\MatchHistoryDTO.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DTOs\\PlayerScoreDTO.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DTOs\\TurnResultDTO.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DTOs\\UserDTO.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DTOs\\WordDTO.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Properties\\AssemblyInfo.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Services\\AccountService.svc.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Services\\CatalogService.svc.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Services\\GameService.svc.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Services\\MatchmakingService.svc.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Services\\ScoreService.svc.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DataAccess\\HangmanModel.Context.tt",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DataAccess\\HangmanModel.tt",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Services\\AccountService.svc",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Services\\CatalogService.svc",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Services\\GameService.svc",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Services\\MatchmakingService.svc",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Services\\ScoreService.svc",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Web.config",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DataAccess\\HangmanModel.edmx.diagram",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\DataAccess\\HangmanModel.edmx",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\packages.config",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Web.Debug.config",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\Web.Release.config",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\bin\\HangmanServer.dll.config",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\.vs\\HangmanServer\\config\\applicationhost.config",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\.vs\\HangmanServer\\v17\\DocumentLayout.backup.json",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\.vs\\HangmanServer\\v17\\DocumentLayout.json",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\packages\\EntityFramework.6.5.2\\tools\\init.ps1",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\packages\\EntityFramework.6.5.2\\tools\\install.ps1",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\packages\\Microsoft.Configuration.ConfigurationBuilders.Environment.3.0.0\\tools\\Net471\\Install.ps1",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\packages\\Microsoft.Configuration.ConfigurationBuilders.Environment.3.0.0\\tools\\Net471\\KeyValueConfigBuildersCommon.ps1",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\packages\\Microsoft.Configuration.ConfigurationBuilders.Environment.3.0.0\\tools\\Net471\\Uninstall.ps1",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\packages\\EntityFramework.6.5.2\\tools\\net6.0\\any\\ef6.runtimeconfig.json"

08BCF73D-F901-40C3-8524-4C064DF723D4.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\.sonarqube\\out\\0"
08BCF73D-F901-40C3-8524-4C064DF723D4.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\.sonarqube\\out\\0\\Issues.json"
08BCF73D-F901-40C3-8524-4C064DF723D4.sonar.cs.scanner.telemetry=\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\.sonarqube\\out\\0\\Telemetry.json"

08BCF73D-F901-40C3-8524-4C064DF723D4.sonar.working.directory=C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanServer\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=08BCF73D-F901-40C3-8524-4C064DF723D4

