//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanServer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        public int MatchID { get; set; }
        public int CreatorID { get; set; }
        public Nullable<int> ChallengerID { get; set; }
        public int WordID { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> WinnerID { get; set; }
        public Nullable<int> AbandonerID { get; set; }
    
        public virtual Users CreatorUser { get; set; }
        public virtual Users ChallengerUser { get; set; }
        public virtual Users WinnerUser { get; set; }
        public virtual MatchStatuses MatchStatuses { get; set; }
        public virtual Users AbandonerUser { get; set; }
        public virtual Words Words { get; set; }
    }
}
